@startuml WorldLogic
state "WorldLogic State" as Yolk_Level_WorldLogic_State {
  state "Transitioning" as Yolk_Level_WorldLogic_State_Transitioning
  state "InWorld" as Yolk_Level_WorldLogic_State_InWorld
  state "OutOfWorld" as Yolk_Level_WorldLogic_State_OutOfWorld
}

Yolk_Level_WorldLogic_State_InWorld --> Yolk_Level_WorldLogic_State_OutOfWorld : Exit
Yolk_Level_WorldLogic_State_InWorld --> Yolk_Level_WorldLogic_State_Transitioning : Transition
Yolk_Level_WorldLogic_State_OutOfWorld --> Yolk_Level_WorldLogic_State_Transitioning : Transition
Yolk_Level_WorldLogic_State_Transitioning --> Yolk_Level_WorldLogic_State_InWorld : OnTransitioned

Yolk_Level_WorldLogic_State_InWorld : OnExit → Clear
Yolk_Level_WorldLogic_State_OutOfWorld : OnEnter → Clear
Yolk_Level_WorldLogic_State_Transitioning : LoadAndEnterLevel() → TransitionLevel

[*] --> Yolk_Level_WorldLogic_State_OutOfWorld
@enduml