@startuml WorldLogic
state "WorldLogic State" as Yolk_Level_WorldLogic_State {
  state "InWorld" as Yolk_Level_WorldLogic_State_InWorld
  state "OutOfWorld" as Yolk_Level_WorldLogic_State_OutOfWorld
  state "Transitioning" as Yolk_Level_WorldLogic_State_Transitioning
}

Yolk_Level_WorldLogic_State_InWorld --> Yolk_Level_WorldLogic_State_Transitioning : Transition
Yolk_Level_WorldLogic_State_OutOfWorld --> Yolk_Level_WorldLogic_State_Transitioning : Transition
Yolk_Level_WorldLogic_State_Transitioning --> Yolk_Level_WorldLogic_State_InWorld : OnTransitioned

Yolk_Level_WorldLogic_State_Transitioning : LoadAndEnterLevel() → TransitionLevel

[*] --> Yolk_Level_WorldLogic_State_OutOfWorld
@enduml