@startuml WorldLogic
state "WorldLogic State" as Yolk_Level_WorldLogic_State {
  state "LoadingLevel" as Yolk_Level_WorldLogic_State_LoadingLevel
  state "OutOfLevel" as Yolk_Level_WorldLogic_State_OutOfLevel
  state "InLevel" as Yolk_Level_WorldLogic_State_InLevel
}

Yolk_Level_WorldLogic_State_InLevel --> Yolk_Level_WorldLogic_State_LoadingLevel : RequestLevelTransition
Yolk_Level_WorldLogic_State_LoadingLevel --> Yolk_Level_WorldLogic_State_InLevel : OnLevelLoaded
Yolk_Level_WorldLogic_State_OutOfLevel --> Yolk_Level_WorldLogic_State_LoadingLevel : RequestLevelTransition

Yolk_Level_WorldLogic_State_LoadingLevel : LoadAndEnterLevel() → LoadLevel

[*] --> Yolk_Level_WorldLogic_State_OutOfLevel
@enduml