@startuml GameLogic
state "GameLogic State" as Yolk_Game_GameLogic_State {
  state "InGame" as Yolk_Game_GameLogic_State_InGame {
    state "Paused" as Yolk_Game_GameLogic_State_InGame_Paused {
      state "Quitting" as Yolk_Game_GameLogic_State_InGame_Paused_Quitting
      state "Over" as Yolk_Game_GameLogic_State_InGame_Paused_Over
    }
    state "Playing" as Yolk_Game_GameLogic_State_InGame_Playing
  }
  state "Loading" as Yolk_Game_GameLogic_State_Loading
  state "Standby" as Yolk_Game_GameLogic_State_Standby
  state "Starting" as Yolk_Game_GameLogic_State_Starting
}

Yolk_Game_GameLogic_State --> Yolk_Game_GameLogic_State_Loading : Load
Yolk_Game_GameLogic_State_InGame --> Yolk_Game_GameLogic_State_InGame : Save
Yolk_Game_GameLogic_State_InGame --> Yolk_Game_GameLogic_State_InGame_Paused_Over : OnGameOverTriggered
Yolk_Game_GameLogic_State_InGame --> Yolk_Game_GameLogic_State_InGame_Paused_Quitting : OnQuitRequested
Yolk_Game_GameLogic_State_InGame_Paused --> Yolk_Game_GameLogic_State_InGame_Playing : OnPauseUserInput
Yolk_Game_GameLogic_State_InGame_Paused_Over --> Yolk_Game_GameLogic_State_InGame_Paused_Quitting : OnQuitRequested
Yolk_Game_GameLogic_State_InGame_Paused_Quitting --> Yolk_Game_GameLogic_State_Standby : QuittingTransitionFinished
Yolk_Game_GameLogic_State_InGame_Playing --> Yolk_Game_GameLogic_State_InGame_Paused : OnPauseUserInput
Yolk_Game_GameLogic_State_Loading --> Yolk_Game_GameLogic_State_InGame_Playing : OnLoaded
Yolk_Game_GameLogic_State_Standby --> Yolk_Game_GameLogic_State_Starting : Start
Yolk_Game_GameLogic_State_Starting --> Yolk_Game_GameLogic_State_InGame_Playing : Ready

Yolk_Game_GameLogic_State : OnGamePausedSync() → SetPauseMode
Yolk_Game_GameLogic_State : OnGameSlotSync() → SetSlot
Yolk_Game_GameLogic_State_InGame : OnGameSaveRequested() → SaveGame
Yolk_Game_GameLogic_State_InGame_Paused_Quitting : OnEnter → QuitGame
Yolk_Game_GameLogic_State_InGame_Playing : OnEnter → UpdateVisibility
Yolk_Game_GameLogic_State_InGame_Playing : OnGameLoadRequested() → LoadGame
Yolk_Game_GameLogic_State_Loading : OnBlackoutFinished() → LoadGame

[*] --> Yolk_Game_GameLogic_State_Standby
@enduml