@startuml ControlsLogic
state "ControlsLogic State" as Yolk_Logic_Controls_ControlsLogic_State {
  state "Listening" as Yolk_Logic_Controls_ControlsLogic_State_Listening {
    state "Key" as Yolk_Logic_Controls_ControlsLogic_State_Listening_Key
  }
  state "Idle" as Yolk_Logic_Controls_ControlsLogic_State_Idle
}

Yolk_Logic_Controls_ControlsLogic_State_Idle --> Yolk_Logic_Controls_ControlsLogic_State_Idle : Listen
Yolk_Logic_Controls_ControlsLogic_State_Idle --> Yolk_Logic_Controls_ControlsLogic_State_Listening_Key : Listen
Yolk_Logic_Controls_ControlsLogic_State_Listening --> Yolk_Logic_Controls_ControlsLogic_State_Idle : Cancel
Yolk_Logic_Controls_ControlsLogic_State_Listening_Key --> Yolk_Logic_Controls_ControlsLogic_State_Idle : PressKey

Yolk_Logic_Controls_ControlsLogic_State_Listening_Key : OnPressKey → ActionMapped

[*] --> Yolk_Logic_Controls_ControlsLogic_State_Idle
@enduml