@startuml ControlsLogic
state "ControlsLogic State" as Yolk_Logic_Controls_ControlsLogic_State {
  state "Listening" as Yolk_Logic_Controls_ControlsLogic_State_Listening
  state "Idle" as Yolk_Logic_Controls_ControlsLogic_State_Idle
}

Yolk_Logic_Controls_ControlsLogic_State_Idle --> Yolk_Logic_Controls_ControlsLogic_State_Listening : Listen
Yolk_Logic_Controls_ControlsLogic_State_Listening --> Yolk_Logic_Controls_ControlsLogic_State_Idle : Press

Yolk_Logic_Controls_ControlsLogic_State_Listening : OnPress → ActionMapped

[*] --> Yolk_Logic_Controls_ControlsLogic_State_Idle
@enduml