@startuml PlayerLogic
state "PlayerLogic State" as Yolk_Logic_Player_PlayerLogic_State {
  state "Disabled" as Yolk_Logic_Player_PlayerLogic_State_Disabled
  state "Enabled" as Yolk_Logic_Player_PlayerLogic_State_Enabled
}

Yolk_Logic_Player_PlayerLogic_State_Enabled --> Yolk_Logic_Player_PlayerLogic_State_Disabled : Kill

Yolk_Logic_Player_PlayerLogic_State : OnWorldLevelLoaded() → Teleport

[*] --> Yolk_Logic_Player_PlayerLogic_State_Enabled
@enduml