@startuml PlayerLogic
state "PlayerLogic State" as Yolk_Logic_Player_PlayerLogic_State {
  state "Disabled" as Yolk_Logic_Player_PlayerLogic_State_Disabled {
    state "Dead" as Yolk_Logic_Player_PlayerLogic_State_Disabled_Dead
    state "Hurt" as Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt
  }
  state "Enabled" as Yolk_Logic_Player_PlayerLogic_State_Enabled {
    state "Alive" as Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive {
      state "Airborne" as Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne {
        state "Falling" as Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling
        state "Jumping" as Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping
      }
      state "Grounded" as Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded {
        state "Idle" as Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Idle
        state "Walking" as Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Walking
      }
      state "OnWall" as Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_OnWall
    }
  }
}

Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt --> Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt : AnimationFinished
Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt --> Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt : PhysicsTick
Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive : BlackoutFinished
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive --> Yolk_Logic_Player_PlayerLogic_State_Disabled_Dead : Die
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive --> Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt : TakeDamage
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive : Move
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne : PhysicsTick
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : HitCeiling
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : Jump
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : Move
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : OnGrounded
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : PhysicsTick
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping : Jump
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Idle : OnGrounded
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : PhysicsTick
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : StopJump
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping : PhysicsTick
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : OnGrounded
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping : Jump
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded : OnGrounded
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Idle : PhysicsTick
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Walking : PhysicsTick
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Walking --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Idle : PhysicsTick
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Walking --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Walking : PhysicsTick

Yolk_Logic_Player_PlayerLogic_State : OnWorldLevelLoaded() → Teleport
Yolk_Logic_Player_PlayerLogic_State_Disabled : OnEnter → SetEnabled
Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt : OnEnter → Animate
Yolk_Logic_Player_PlayerLogic_State_Disabled_Hurt : OnPhysicsTick → MoveAndSlide
Yolk_Logic_Player_PlayerLogic_State_Enabled : OnEnter → SetEnabled
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne : OnPhysicsTick → FaceLeft, FaceRight, MoveAndSlide
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : OnEnter → Animate
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Falling : OnPhysicsTick → FaceLeft, FaceRight, MoveAndSlide
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping : OnEnter → Animate, OnJump
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Airborne_Jumping : OnPhysicsTick → MoveAndSlide
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Idle : OnEnter → Animate
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Walking : OnEnter → Animate
Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded_Walking : OnPhysicsTick → FaceLeft, FaceRight, MoveAndSlide

[*] --> Yolk_Logic_Player_PlayerLogic_State_Enabled_Alive_Grounded
@enduml