@startuml ActionContainerLogic
state "ActionContainerLogic State" as Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State {
  state "Idle" as Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Idle
  state "Listening" as Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Listening
}

Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Idle --> Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Listening : Listen
Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Listening --> Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Idle : Stop
Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Listening --> Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Listening : Bind

Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State : OnDefaultsRestored() → OnDefaultRestored
Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Listening : OnActionMapped() → UpdateInputPrompt
Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Listening : OnEnter → UpdateInputPrompt
Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Listening : OnExit → UpdateInputPrompt

[*] --> Yolk_UI_Options_ActionBindButton_ActionContainerLogic_State_Idle
@enduml