name: '🧑‍🏫 Spellcheck'
on: workflow_dispatch
  # push:
  #   branches:
  #     main

jobs:
  spellcheck:
    name: '🧑‍🏫 Spellcheck'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - uses: actions/checkout@v4
        name: 🧾 Checkout

      - uses: streetsidesoftware/cspell-action@v6
        name: 📝 Check Spelling
        with:
          config: './cspell.json'
          incremental_files_only: false
          root: '.'
