@startuml OptionsMenuLogic
state "OptionsMenuLogic State" as Yolk_UI_OptionsMenuLogic_State {
  state "Visible" as Yolk_UI_OptionsMenuLogic_State_Visible
  state "Hidden" as Yolk_UI_OptionsMenuLogic_State_Hidden
}

Yolk_UI_OptionsMenuLogic_State_Hidden --> Yolk_UI_OptionsMenuLogic_State_Visible : Show
Yolk_UI_OptionsMenuLogic_State_Visible --> Yolk_UI_OptionsMenuLogic_State_Hidden : Hide
[*] --> Yolk_UI_OptionsMenuLogic_State_Hidden
@enduml
